# --- Actuator and Observation Settings ---
management:
  info:
    env:
      enabled: true

    git:
      enabled: true
      mode: full

  observations:
    key-values:
      application: wine-store-service
    http:
      client:
        enabled: true
      server:
        enabled: true
    jdbc:
      enabled: true

  tracing:
    sampling:
      probability: 1.0
    zipkin:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}

  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - loggers

    metrics:
      distribution:
        percentiles-histogram:
          all: true
        slo:
          "[http.server.requests]": 50ms, 100ms, 500ms, 1s, 2s
          "[jdbc.connections.usage]": 100ms, 500ms, 1s
      enable:
        all: true
      enabled: true
    health:
      show-details: always

  metrics:
    enable:
      all: true

    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
        jdbc.connections.acquire: true
        jdbc.connections.usage: true
        hikaricp.connections.usage: true
        jdbc.query: true
        jdbc.connections.acquire.seconds: true
        jdbc.connections.usage.seconds: true

    data:
      repository:
        autotime:
          enabled: true

jdbc:
  includes-parameters: true

loki:
  url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.hibernate.sql: info
    root: info

spring:
  datasource:
    hikari:
      metrics-tracking: true
    observation:
      enabled: true

info:
  app:
    name: "stoic-winery-api"
    version: "0.0.1-SNAPSHOT"
    description: "Core Modular Monolith backend for the Stoic Winery project. Handles business logic, JWT security, MySQL persistence with Liquibase, and Telegram notifications."