services:
  db-sql:
    env_file: .env
    container_name: mysql-winery-db-container
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  api-backend:
    env_file: .env
    container_name: winery-api-container
    depends_on:
      db-sql:
        condition: service_healthy
      loki:
        condition: service_started
      tempo:
        condition: service_started
    restart: on-failure
    build: ./stoic-winery-api
    ports:
      - "${BACKEND_PORT:-8080}:8080"
      - "5006:5005"
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411/api/v2/spans
      LOKI_URL: http://loki:3100/loki/api/v1/push
      JAVA_TOOL_OPTIONS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    volumes:
      - wine_images:/app/upload/images/wine
    networks:
      - backend

  winery-admin-ui:
    container_name: winery-admin-ui-container
    build: ./winery-admin-ui
    ports:
      - "${ADMIN_UI_PORT:-8081}:8081"
    environment:
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411/api/v2/spans
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - BACKEND_URL=http://api-backend:8080/api
    networks:
      - backend
    depends_on:
      - loki
      - tempo
      - api-backend

  prometheus:
    image: prom/prometheus:v2.46.0
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
    depends_on:
      - api-backend
    networks:
      - backend

  loki:
    image: grafana/loki:main
    command: [ '-config.file=/etc/loki/local-config.yaml' ]
    ports:
      - '3100:3100'
    networks:
      - backend

  tempo:
    image: grafana/tempo:2.2.2
    command: [ '-config.file=/etc/tempo.yaml' ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - '3200:3200'
      - '9411:9411'
    networks:
      - backend

  grafana:
    image: grafana/grafana:12.0.0
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - '3030:3000'
    depends_on:
      - prometheus
      - loki
      - tempo
      - api-backend
    networks:
      - backend

  frontend-wine-site:
    env_file: .env
    build: ./wine_site_project
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    stdin_open: true
    tty: true
    networks:
      - frontend
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  mysql_data:
  wine_images:
