version: "3.8"

services:
  db_sql:
    env_file: .env
    container_name: mysql-winery-db-container
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3309:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-db

  api_backend:
    env_file: .env
    container_name: winery-api-container
    depends_on:
      db_sql:
        condition: service_healthy
    restart: on-failure
    build: ./stoic-winery-api
    ports:
      - "${BACKEND_PORT:-8080}:8080"
      - "5006:5005"
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    networks:
      - backend-db

  frontend_wine_site:
    build: ./wine_site_project
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    stdin_open: true
    tty: true
    depends_on:
      api_backend:
        condition: service_started
    networks:
      - frontend-api

networks:
  backend-db:
    driver: bridge
  frontend-api:
    driver: bridge

volumes:
  mysql_data:
