### Create New Order
POST {{base_url}}/orders
Content-Type: application/json

{
  "userFirstAndLastName": "Ivan Petrov",
  "email": "customer@email.com",
  "phoneNumber": "+380509876543",
  "createShoppingCardDto": {
    "purchaseObjects": [
      {
        "wineId": 2,
        "quantity": 1
      }
    ]
  },
  "createOrderDeliveryInformationDto": {
    "zipCode": "00000",
    "region": "Kyiv region",
    "city": "Kyiv",
    "street": "Lobanovskogo str, 13/1, ap. 16",
    "comment": "string"
  }
}

### Get All Orders
GET {{base_url}}/orders?page=0&size=20
Authorization: Bearer {{auth_token}}

### Get Orders by User ID
GET {{base_url}}/orders/users/1
Authorization: Bearer {{auth_token}}

### Get Order by ID
GET {{base_url}}/orders/1
Authorization: Bearer {{auth_token}}

### Set Status PAID (MANAGER only)
PATCH {{base_url}}/orders/1/paid
Authorization: Bearer {{auth_token}}

### Delete Order (MANAGER only)
DELETE {{base_url}}/orders/1
Authorization: Bearer {{auth_token}}