### Add Review to Wine
POST {{base_url}}/reviews
Content-Type: application/json

{
  "wineId": 1,
  "userFirstAndLastName": "Ivan Ivanov",
  "message": "Great wine, I really enjoyed the aroma!",
  "rating": 5
}

### Get Reviews for Wine
GET {{base_url}}/reviews/wines/1?size=4&page=0