### Get All Wines (with pagination)
GET {{base_url}}/wines?page=0&size=10&sort=id,desc

### Get Wine by ID
GET {{base_url}}/wines/1

### Create New Wine (MANAGER only)
POST {{base_url}}/wines
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "vendorCode": "MSD 2025",
  "qualityLevel": "Premium",
  "reserveType": "Limited Edition Wine",
  "name": "Prince Trubetskoi Select Riesling",
  "shortName": "Prince Trubetskoi",
  "year": 2017,
  "tasteWine": "fish",
  "price": 25.59,
  "grape": "Riesling",
  "isDecantation": false,
  "wineType": "DRY",
  "strengthFrom": 10.9,
  "strengthTo": 11.8,
  "wineColor": "WHITE",
  "colorDescribing": "Deep yellow with greenish hues",
  "taste": "Delicate, balanced, round, with a fruity and honey aftertaste.",
  "aroma": "Soft, generous, multifaceted, with hints of tropical fruits.",
  "gastronomy": "Goes well with fish dishes, mature cheeses and stews.",
  "description": "Elegant Riesling from Prince Trubetskoi winery, showcasing refined balance and aromatic complexity.",
  "pictureLink": "https://example.com/images/wine_front.jpg",
  "pictureLink2": "https://example.com/images/wine_label.jpg"
}

### Delete Wine (MANAGER only)
DELETE {{base_url}}/wines/33
Authorization: Bearer {{auth_token}}

### Update Wine Images (MANAGER only)
PATCH http://localhost:8080/api/wines/37/image
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="imageA"; filename="Pinot-Noir-Red-Dry2big.png"
Content-Type: image/png

< C:/Users/artem/Downloads/Pinot-Noir-Red-Dry2big.png
--boundary
Content-Disposition: form-data; name="imageB"; filename="Pinot-Noir-Red-Dry3small.png"
Content-Type: image/png

< C:/Users/artem/Downloads/Pinot-Noir-Red-Dry3small.png
--boundary--
