{
 "title": "Wine Service USE Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Service Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (contextual_name) (rate({__name__=~\"wine_.*_seconds_sum\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "CPU usage by the application process.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Thread Saturation",
   "type": "timeseries",
   "description": "Number of currently active and running threads within the JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap Saturation",
   "type": "timeseries",
   "description": "Used vs Max Heap Memory.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"} / jvm_memory_max_bytes{area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Pool Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "hikaricp_connections_active / hikaricp_connections_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pause Duration",
   "type": "timeseries",
   "description": "Time spent in Garbage Collection, which causes \"stop-the-world\" pauses.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Pool Saturation",
   "type": "timeseries",
   "description": "Active vs Max database connections (HikariCP)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{pool=\"HikariPool-1\"} / hikaricp_connections_max{pool=\"HikariPool-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image Storage IO",
   "type": "timeseries",
   "description": "Rate of image processing operations in the ImageStorageService.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"image_.*_seconds_count\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internal Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (errorMessage) (rate({__name__=~\"wine_.*_seconds_count\", status=\"error\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}