{
 "title": "Wine Service RED Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Latency P50 (Median)",
   "type": "timeseries",
   "description": "The median response time (50th percentile), representing the typical user experience.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate({__name__=~\"wine_.*_seconds_bucket\", application=\"wine-store\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency P95 (Performance) ",
   "type": "timeseries",
   "description": "95th percentile of response time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) \r\n(rate(\r\n  {__name__=~\"wine_.*_seconds_bucket\"}\r\n  [1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Wine Rating",
   "type": "timeseries",
   "description": "Real-time average rating score for wines.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "wine_average_rating", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Rate (Throughput)",
   "type": "timeseries",
   "description": "Total number of requests per second to the Wine Controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"wine_.*_seconds_count\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wine Inventory Count (Business Metric)",
   "type": "barchart",
   "description": "Total number of wines in the database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "wine_total_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error Rate (Failures)  ",
   "type": "timeseries",
   "description": "Percentage of failed requests (status codes other than 2xx) for wine operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"wine_.*_seconds_count\", status!~\"2..\"}[1m]))\r\n/\r\nsum(rate({__name__=~\"wine_.*_seconds_count\"}[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}