global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'wine-store-api'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
        labels:
          application: 'wine-store (docker)'
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'wine-store (intellij)'
