spring:
  application:
    name: winery-admin-ui

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  config:
    import:
      - optional:classpath:/application-actuator.yaml

server:
  port: 8081

api:
  backend-url: ${BACKEND_URL:http://localhost:8080/api}
  filter:
    public:
      paths:
        - /actuator
        - /login
        - /static
        - /css
        - /js
        - /favicon.ico

feign:
  client:
    config:
      default:
        loggerLevel: full
  auth:
    skip-urls:
      - /health
